# Gradle Options
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

# Project
mod_version=26.1-r1.0
project_group=net.rebel459.fractured
license=Legacy License
java_version=25

# Mod
mod_author=Rebel459
mod_id=fractured
mod_name=Fractured
mod_description=A highly configurable reimagining of how you acquire the eyes of ender in order to find the stronghold and light its portal.

# Minecraft
minecraft_version=26.1
neo_form_version=26.1-1

# Fabric
fabric_loader=0.18.5
fabric_api=0.145.1+26.1
fabric_minecraft_version=>=26.1 <26.2

# NeoForge
neoforge_version=26.1.0.19-beta
neoforge_minecraft_version=[26.1, 26.2)

# Common Dependencies
unified_version=26.1-r2.0
cloth_version=26.1.154

# Fabric Dependencies
modmenu_version=18.0.0-alpha.8